// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/brand-lookup": {
    params: {};
  };
  "/composition-lookup": {
    params: {};
  };
  "/product-catalogus": {
    params: {};
  };
  "/product-catalogus/categorieen/:categoryId/bewerken": {
    params: {
      "categoryId": string;
    };
  };
  "/product-catalogus/nieuw": {
    params: {};
  };
  "/product-catalogus/:productId": {
    params: {
      "productId": string;
    };
  };
  "/locations": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/brand-lookup" | "/composition-lookup" | "/product-catalogus" | "/product-catalogus/categorieen/:categoryId/bewerken" | "/product-catalogus/nieuw" | "/product-catalogus/:productId" | "/locations";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/layout/layout.tsx": {
    id: "routes/layout/layout";
    page: "/" | "/brand-lookup" | "/composition-lookup" | "/product-catalogus" | "/product-catalogus/categorieen/:categoryId/bewerken" | "/product-catalogus/nieuw" | "/product-catalogus/:productId" | "/locations";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/brand-lookup.ts": {
    id: "routes/brand-lookup";
    page: "/brand-lookup";
  };
  "routes/composition-lookup.ts": {
    id: "routes/composition-lookup";
    page: "/composition-lookup";
  };
  "routes/product-catalog/product-catalog.tsx": {
    id: "routes/product-catalog/product-catalog";
    page: "/product-catalogus";
  };
  "routes/product-catalog/edit-category.tsx": {
    id: "routes/product-catalog/edit-category";
    page: "/product-catalogus/categorieen/:categoryId/bewerken";
  };
  "routes/new-product/new-product.tsx": {
    id: "routes/new-product/new-product";
    page: "/product-catalogus/nieuw";
  };
  "routes/product-detail/product-detail.tsx": {
    id: "routes/product-detail/product-detail";
    page: "/product-catalogus/:productId";
  };
  "routes/locations.tsx": {
    id: "routes/locations";
    page: "/locations";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/layout/layout": typeof import("./app/routes/layout/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/brand-lookup": typeof import("./app/routes/brand-lookup.ts");
  "routes/composition-lookup": typeof import("./app/routes/composition-lookup.ts");
  "routes/product-catalog/product-catalog": typeof import("./app/routes/product-catalog/product-catalog.tsx");
  "routes/product-catalog/edit-category": typeof import("./app/routes/product-catalog/edit-category.tsx");
  "routes/new-product/new-product": typeof import("./app/routes/new-product/new-product.tsx");
  "routes/product-detail/product-detail": typeof import("./app/routes/product-detail/product-detail.tsx");
  "routes/locations": typeof import("./app/routes/locations.tsx");
};