import { mkdir, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { detectSupportedImage } from "./package-image-validation.ts";

const maximumImageBytes = 5 * 1024 * 1024;
const storedFileNamePattern = /^[0-9a-f-]+\.(?:png|jpg|webp)$/;

/** Result of validating and storing one package image. */
export type PackageImageUploadResult =
  | { readonly ok: true; readonly imageUrl: string }
  | { readonly ok: false; readonly message: string };

/** Package-image storage operations used by catalog HTTP routes. */
export type PackageImageService = {
  readonly deleteImage: (imageUrl: string) => Promise<void>;
  readonly storeImage: (file: File) => Promise<PackageImageUploadResult>;
  readonly readImage: (fileName: string) => Promise<{ readonly file: Blob; readonly mediaType: string } | null>;
};

/**
 * Create local package-image storage alongside the configured SQLite database.
 *
 * @param databasePath - Path to the catalog SQLite database.
 * @param publicBaseUrl - Public backend URL used in persisted image URLs.
 * @returns Package-image storage operations scoped to the configured database.
 */
export function createPackageImageService(databasePath: string, publicBaseUrl: string): PackageImageService {
  const storageDirectory = resolve(dirname(databasePath), "package-images");
  const normalizedBaseUrl = publicBaseUrl.replace(/\/$/, "");
  const imageUrlPrefix = `${normalizedBaseUrl}/package-images/`;

  /**
   * Validate and persist one package image under a generated name.
   *
   * @param file - Uploaded image candidate.
   * @returns The immutable public URL or a safe validation message.
   */
  async function storeImage(file: File): Promise<PackageImageUploadResult> {
    if (file.size === 0) return { ok: false, message: "Kies een afbeelding." };
    if (file.size > maximumImageBytes) return { ok: false, message: "De afbeelding mag maximaal 5 MB zijn." };

    const bytes = new Uint8Array(await file.arrayBuffer());
    const image = detectSupportedImage(bytes);
    if (image === null) return { ok: false, message: "Gebruik een geldige PNG-, JPEG- of WebP-afbeelding." };

    await mkdir(storageDirectory, { recursive: true });
    const fileName = `${crypto.randomUUID()}.${image.extension}`;
    await Bun.write(resolve(storageDirectory, fileName), bytes);
    return { ok: true, imageUrl: `${imageUrlPrefix}${fileName}` };
  }

  /**
   * Read a generated package image without allowing path traversal.
   *
   * @param fileName - Server-generated image file name.
   * @returns Stored image content and media type, or null when absent.
   */
  async function readImage(fileName: string): Promise<{ readonly file: Blob; readonly mediaType: string } | null> {
    if (!storedFileNamePattern.test(fileName)) return null;
    const file = Bun.file(resolve(storageDirectory, fileName));
    if (!await file.exists()) return null;
    return { file, mediaType: mediaTypeForFileName(fileName) };
  }

  /**
   * Delete an image generated by this service while ignoring external URLs.
   *
   * @param imageUrl - Persisted image URL that may refer to local storage.
   * @returns A promise that resolves after best-effort removal.
   */
  async function deleteImage(imageUrl: string): Promise<void> {
    if (!imageUrl.startsWith(imageUrlPrefix)) return;
    const fileName = imageUrl.slice(imageUrlPrefix.length);
    if (!storedFileNamePattern.test(fileName)) return;
    try {
      await rm(resolve(storageDirectory, fileName), { force: true });
    } catch (error) {
      console.error("Failed to delete a managed package image", { error, fileName });
    }
  }

  return { deleteImage, storeImage, readImage };
}

/**
 * Derive a response media type from a server-generated extension.
 *
 * @param fileName - Validated server-generated file name.
 * @returns HTTP media type for the stored extension.
 */
function mediaTypeForFileName(fileName: string): string {
  if (fileName.endsWith(".png")) return "image/png";
  if (fileName.endsWith(".webp")) return "image/webp";
  return "image/jpeg";
}
